<?php

namespace Szkolenie\MiastaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SongsController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Szkolenie\MiastaBundle\Controller\SongsController();
        return $instance;
    }
}
